rootProject.name = "protoactor-kotlin"

include("proto-mailbox")
include("proto-actor")
include("proto-router")
include("proto-remote")
include("proto-cluster")
include("proto-persistence")
include("proto-stream")
include("proto-benchmarks")
include("proto-plugin")
include("proto-plugin-examples")
include("proto-cluster-libp2p")
include("examples")
include("native-example")
include("simple-native")
include("benchmark-native")
include("dataflare")
