Args = --no-fallback \
       --report-unsupported-elements-at-runtime \
       -H:+ReportExceptionStackTraces \
       -H:+PrintClassInitialization \
       --initialize-at-build-time=org.slf4j,ch.qos.logback \
       --initialize-at-run-time=io.grpc,io.netty
