plugin.id=proto-plugin-examples
plugin.version=0.1.0
plugin.class=actor.proto.plugin.examples.ExamplePlugin
plugin.provider=ProtoActor-Kotlin Team
plugin.dependencies=
plugin.description=Example plugins for ProtoActor-Kotlin
