Args = --initialize-at-build-time=org.slf4j,ch.qos.logback \
       --initialize-at-run-time=io.netty,com.sun.jmx,com.sun.management \
       --allow-incomplete-classpath \
       -H:+ReportExceptionStackTraces \
       -H:+JNI \
       -H:+ReportUnsupportedElementsAtRuntime \
       -H:+AllowIncompleteClasspath \
       -H:IncludeResources=workflows/.*\\.(yaml|dsl)|input/.*\\.csv \
       -H:+IncludeAllTimeZones \
       -H:Class=com.dataflare.native.NativeApp
